console.log('Hello Winc Academy');
let name = ('Charles');
console.log(name);
let lengte = 6;
let breedte = 5;
console.log(lengte * breedte);
console.log(lengte + breedte);
console.log(breedte - lengte);
let leeftijdnr = 48;
console.log(typeof leeftijdnr);
let leeftijdstring = "48";
console.log(typeof leeftijdstring);
